title       = Lean Core
description = Мінімальна серверна база на Luanti: default, player_api, spawn. Голий каркас для подальшого розширення модами.
min_minetest_version = 5.8
textdomain = game_description
aliases =
author = Vasyl
release = 1