title = Lean Core
description = A minimal, high-performance base for Luanti servers with only default, player_api and spawn mods.
min_minetest_version = 5.8
textdomain = game_description
aliases =
author = 8a7l
release = 1
